# Generated by Django 5.0.4 on 2024-04-13 15:57

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_id', models.SlugField()),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('tg_full_name', models.CharField(max_length=120)),
                ('tg_username', models.CharField(blank=True, max_length=120, null=True)),
                ('region', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=13)),
                ('math_score', models.IntegerField(blank=True, null=True)),
                ('iq_score', models.IntegerField(blank=True, null=True)),
                ('english_score', models.IntegerField(blank=True, null=True)),
                ('total_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_ban', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
