# Generated by Django 5.0.4 on 2024-04-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_user_options_alter_user_total_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-total_score']},
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.SlugField(unique=True),
        ),
    ]
